from flask import redirect
from app.factory import (
    create_app,
    call_gemini_grounded_once,
    current_user_daily_limit,
    AI_CALL_TIMEOUT_SEC,
    GLOBAL_DAILY_LIMIT,
    USER_DAILY_LIMIT,
    MAX_CACHE_DAYS,
    PER_IP_PER_MIN_LIMIT,
    QUOTA_RESERVATION_TTL_SECONDS,
    MAX_ACTIVE_RESERVATIONS,
)
from app.extensions import db, login_manager, oauth, migrate, ai_client, advisor_client
from app.models import User, SearchHistory, AdvisorHistory, DailyQuotaUsage, QuotaReservation, IpRateLimit
from app.quota import (
    resolve_app_timezone,
    compute_quota_window,
    reserve_daily_quota,
    finalize_quota_reservation,
    release_quota_reservation,
    check_and_increment_ip_rate_limit,
    log_access_decision,
    cleanup_expired_reservations,
    rollback_quota_increment,
    get_daily_quota_usage,
    get_client_ip,
    parse_owner_emails,
    ModelOutputInvalidError,
    QuotaInternalError,
)

__all__ = [
    "create_app",
    "call_gemini_grounded_once",
    "db",
    "login_manager",
    "oauth",
    "migrate",
    "User",
    "SearchHistory",
    "AdvisorHistory",
    "DailyQuotaUsage",
    "QuotaReservation",
    "IpRateLimit",
    "resolve_app_timezone",
    "compute_quota_window",
    "reserve_daily_quota",
    "finalize_quota_reservation",
    "release_quota_reservation",
    "check_and_increment_ip_rate_limit",
    "log_access_decision",
    "cleanup_expired_reservations",
    "rollback_quota_increment",
    "get_daily_quota_usage",
    "get_client_ip",
    "parse_owner_emails",
    "ModelOutputInvalidError",
    "QuotaInternalError",
    "AI_CALL_TIMEOUT_SEC",
    "GLOBAL_DAILY_LIMIT",
    "USER_DAILY_LIMIT",
    "MAX_CACHE_DAYS",
    "PER_IP_PER_MIN_LIMIT",
    "QUOTA_RESERVATION_TTL_SECONDS",
    "MAX_ACTIVE_RESERVATIONS",
    "ai_client",
    "advisor_client",
    "current_user_daily_limit",
    "redirect",
]
